<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <style>
          #body{
          background-image: url('/img/foto.jpg');
          background-repeat: no-repeat;
          background-size: cover;
          height:90vh;
          width: 100%;
          }

          .card{
            opacity: 0.7;
          }
        </style>
    </head>
    <body id="body">

      <div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cadastro realizado com sucesso!</h2>
            <h6>Bem vindo ao Twitter, aqui é um lugar onde você poderá
            se comunicar, se expressar e o mais importante de todos: Ser muito feliz!</h6>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block">Clique aqui para fazer login em sua nova conta.</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
        
    </body>
</html>



    
  