<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>Inscreva-se</title>

    <style>
        .body{
            background-color: #87CEFA; 
            background-image: url("/img/fundo2.jpg");
            height: 80vh;
        }

        .txtEmail{
            text-align: center;
        }

        .row{
            margin-bottom: 1%;
        }        

    </style>

</head>
<body class="body">

  <div class="container">
      <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 30rem; background-color:GhostWhite;">
          <div class="card-body">

              <div class="row">
                  <div class="col">
                    <h4 class="txtEmail">Digite seu e-mail cadastrado.</h4>
                </div>
            </div>

            <div class="row">
              <div class="col">

                <form action="/novaSenha" method="post">
                  <div class="form-group">
                      <input type="email" name="email" class="form-control" placeholder="E-mail" required="email">
                  </div>

                  <button type="submit" class="btn btn-success btn-block">Enviar</button>

                  <div class="mt-4 mb-4">
                    <small class="form-text">
                        <b> Ao clicar em enviar, estaremos enviando um e-mail para a sua caixa de entrada com o código de verificação.
                        Use este código para fazer a alteração da sua senha.</b>
                    </small>
                </div>
                  
                  <?php if($this->view->verifica == "erro") { ?>
                  <div class="row">
                    <div class="col">
                        <span class="text text-danger">Você digitou um código ou um e-mail inválido.
                        Digite novamente seu e-mail para que um novo código seja gerado.</span>
                    </div>
                </div>
                  <?php } ?>
            </form>

                  
        </div>
    </div>

</div>
</div>
</div>
</div>
</body>
</html>