<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Inscreva-se</title>

        <style>
        .body{
          background-image: url("/img/tt.jpg");
          background-repeat: no-repeat;
          background-size: cover;
          height:80vh;
        }   
        </style>
    </head>
<body class="body">

  <div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem; background-color:GhostWhite;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/icone.jpg" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                  <input type="text" name="nome" class="form-control" placeholder="Nome" required="nome">
              </div>
              
              <div class="form-group">
                  <input type="email" name="email" class="form-control" placeholder="E-mail" required="email">
              </div>

              <div class="form-group">
                  <input type="password" name="senha" class="form-control" placeholder="Senha" required="senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              
              <?php
              
              if($this->view->erroCadastro == true){ ?>
                  
              <small class="form-text text-danger"> Erro ao tentar realizar o cadastro,
                  verifique se os campos foram preenchidos corretamente. </small>
              
              <?php } ?>
              
              
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
    </body>
</html>