<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>Inscreva-se</title>

    <style>
        .body{
            background-color: #87CEFA; 
            background-image: url("/img/fundo2.jpg");
            height: 80vh;
        }

        .txtEmail{
            text-align: center;
        }

        .row{
            margin-bottom: 1%;
        }        

    </style>

</head>
<body class="body">

  <div class="container">
      <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 30rem; background-color:GhostWhite;">
          <div class="card-body">

              <div class="row">
                  <div class="col">
                    <h4 class="txtEmail">Digite o código recebido por e-mail.</h4>
                </div>
            </div>

            <div class="row">
              <div class="col">

                <form action="/alterarSenha" method="post">
                    <input type="hidden" name="id" value="<?= $this->view->teste ?>"/>
                  <div class="form-group">
                      <input type="number" name="codigo" class="form-control" placeholder="Código" required>
                  </div>
                  <div class="form-group">
                      <input type="text" name="novaSenha1" class="form-control" placeholder="Digite sua nova senha" required="novaSenha">
                  </div>  

                  <div class="form-group">
                      <input type="text" name="novaSenha" class="form-control" placeholder="Confirme sua senha" required="novaSenha">
                  </div>  

                  <button type="submit" class="btn btn-success btn-block">Enviar</button>

                  <div class="mt-4 mb-4">
                    <small class="form-text">
                        <b> Digite uma senha com no mínimo 5 caracteres. Dica: Faça uma senha com letras e números.</b>
                    </small>
                  </div>
            </form>
                  
                  <?php if( $this->view->verifica_senha == 'erro') { ?>
                  <div class="mt-4 mb-4">
                    <small class="form-text text-danger">
                        <b> As senhas que você digitou não coincidem. Certifique-se que está digitando a mesma senha
                        nos dois campos.</b>
                    </small>
                  </div>
                  <?php } ?>
        </div>
    </div>
</div>
</div>
</div>
</div>
</body>
</html>