<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Quem seguir</title>

        <!--Importação do arquivo de css desta página -->
        <link rel="stylesheet" href="/css/estiloQuemSeguir.css" />

    </head>
    <body class="body">

        <nav class="navbar navbar-expand-lg menu justify-content-end">
            <div class="navbar-nav">
                <a class="menuItem align-items-right" href="/timeline">
                    Home
                </a>

                <a class="menuItem" href="/sair">
                    Sair
                </a>
                <img src="/img/logo2.png" class="menuIco" />
            </div> 
        </nav>

        <div class="container mt-5">
            <div class="row pt-2">

                <div class="col-md-3">

                    <div class="perfil">
                        <div class="perfilTopo">

                        </div>

                        <div class="perfilPainel">

                            <div class="row mt-2 mb-2">
                                <div class="col mb-2">
                                    <span class="perfilPainelNome"><?= $_SESSION['nome'] ?></span>
                                </div>
                            </div>

                            <div class="row mb-2">

                                <div class="col">
                                    <span class="perfilPainelItem">Tweets</span><br />
                                    <span class="perfilPainelItemValor">
                                        <?=$this->view->total_tweets['total_tweets'] ?>
                                    </span>
                                </div>

                                <div class="col">
                                    <span class="perfilPainelItem">Seguindo</span><br />
                                    <span class="perfilPainelItemValor">
                                        <?= ($this->view->total_seguindo['total_seguindo'])  ?>
                                    </span>
                                </div>

                                <div class="col">
                                    <span class="perfilPainelItem">Seguidores</span><br />
                                    <span class="perfilPainelItemValor">
                                        <?= ($this->view->total_seguidores['total_seguidores'])  ?>
                                    </span>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

                <div class="col-md-6">

                    <div class="row mb-2">
                        <div class="col">
                            <div class="card">
                                <div class="card-body">
                                    <form method="get" action="/quem_seguir">
                                        <div class="input-group mb-3">
                                            <input type="text" name="pesquisarPor" class="form-control txtArea" placeholder="Quem você está procurando?">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary" type="submit">Pesquisar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php foreach ($this->view->usuarios as $indice_array => $usuario) { ?>

                        <div class="row mb-3">
                            <div class="col">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <b><?= $usuario['nome'] ?></b>
                                            </div>
                                            <div class="col-md-12 col-sm-12 d-flex justify-content-end">
                                                <div>
           <!-- Fazendo a verificação se o usuário está sendo seguido ou não.  -->                                         
                                                                                          
          <?php if($usuario['seguindo_s_ou_n'] == 0){ ?>                                          
          <a href="/acao?acao=seguir&id_usuario=<?= $usuario['id'] ?>" class="btn btn-success">Seguir</a>
          <?php } ?>
          
          <?php if($usuario['seguindo_s_ou_n'] == 1){ ?>    
          <a href="/acao?acao=deixar_de_seguir&id_usuario=<?= $usuario['id'] ?>" class="btn btn-danger">Deixar de seguir</a>
          <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>

                </div>
            </div>
        </div>

    </body>
</html>










